export const patients = [
  {
    patientId: 1,
    patientName: "Taite Witson",
    age: 66,
    studyDate: "2022-03-05T07:57:36Z",
    recommendation:
      "Destruction of Cerebral Ventricle, Percutaneous Endoscopic Approach",
    modality: "Aspiration of breast",
    orderingDoctor: "Luis Aldwich",
  },
  {
    patientId: 2,
    patientName: "Adham McCay",
    age: 59,
    studyDate: "2021-10-01T12:36:08Z",
    recommendation:
      "Revision of Radioactive Element in Pelvic Cavity, Percutaneous Approach",
    modality: "Type 3 tympanoplasty",
    orderingDoctor: "Garvin Iddins",
  },
  {
    patientId: 3,
    patientName: "Torey Gyford",
    age: 66,
    studyDate: "2022-04-15T15:17:10Z",
    recommendation: "Release Left Hand Tendon, Percutaneous Approach",
    modality: "X-ray study of eye",
    orderingDoctor: "Shaylyn Challace",
  },
  {
    patientId: 4,
    patientName: "Eleonora Tulleth",
    age: 27,
    studyDate: "2022-01-18T09:17:57Z",
    recommendation:
      "Magnetic Resonance Imaging (MRI) of Lower Extremity Connective Tissue using Other Contrast, Unenhanced and Enhanced",
    modality: "Thorac esophagoenter NEC",
    orderingDoctor: "Tomas Peteri",
  },
  {
    patientId: 5,
    patientName: "Whitney Brychan",
    age: 54,
    studyDate: "2021-10-04T19:37:53Z",
    recommendation:
      "Supplement Left Parietal Bone with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach",
    modality: "Thoraco robotic ast proc",
    orderingDoctor: "Martelle Rix",
  },
  {
    patientId: 6,
    patientName: "Rory Garriock",
    age: 65,
    studyDate: "2022-06-11T08:08:02Z",
    recommendation:
      "Therapeutic Exercise Treatment of Circulatory System - Whole Body using Mechanical Equipment",
    modality: "Conjunctival op NEC",
    orderingDoctor: "Gaby Garham",
  },
  {
    patientId: 7,
    patientName: "Gardner Vedyaev",
    age: 73,
    studyDate: "2022-05-16T01:51:59Z",
    recommendation:
      "Removal of Artificial Sphincter from Urethra, Percutaneous Endoscopic Approach",
    modality: "Speech defect training",
    orderingDoctor: "Cornelle Seiffert",
  },
  {
    patientId: 8,
    patientName: "Nickolai Milesap",
    age: 36,
    studyDate: "2021-10-19T16:14:09Z",
    recommendation:
      "Fusion of 2 or more Lumbar Vertebral Joints, Posterior Approach, Posterior Column, Open Approach",
    modality: "Rem cath cranial cav/tis",
    orderingDoctor: "Tiebout McIndrew",
  },
  {
    patientId: 9,
    patientName: "Roberta Torrisi",
    age: 77,
    studyDate: "2022-01-25T20:55:07Z",
    recommendation:
      "Bypass Descending Colon to Sigmoid Colon with Autologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic",
    modality: "Ovarian torsion release",
    orderingDoctor: "Mathias Flicker",
  },
  {
    patientId: 10,
    patientName: "Major Seilmann",
    age: 82,
    studyDate: "2022-04-11T08:23:20Z",
    recommendation: "Release Left Sphenoid Bone, Open Approach",
    modality: "Other post segment ops",
    orderingDoctor: "Gene Tschersich",
  },
  {
    patientId: 11,
    patientName: "Amalle Ridgewell",
    age: 60,
    studyDate: "2022-03-10T13:24:55Z",
    recommendation:
      "Replacement of Scalp Subcutaneous Tissue and Fascia with Synthetic Substitute, Open Approach",
    modality: "Perineal urethroscopy",
    orderingDoctor: "Falkner Tchaikovsky",
  },
  {
    patientId: 12,
    patientName: "Washington Stoodley",
    age: 50,
    studyDate: "2022-01-20T11:04:26Z",
    recommendation:
      "Dilation of Left Temporal Artery, Bifurcation, with Two Drug-eluting Intraluminal Devices, Open Approach",
    modality: "Open biopsy of esophagus",
    orderingDoctor: "Norina Tynemouth",
  },
  {
    patientId: 13,
    patientName: "Wendye Dudmarsh",
    age: 22,
    studyDate: "2021-10-03T05:15:51Z",
    recommendation: "Extirpation of Matter from Jejunum, Open Approach",
    modality: "Bact smear-female genit",
    orderingDoctor: "Theo Shier",
  },
  {
    patientId: 14,
    patientName: "Simona Grimmer",
    age: 62,
    studyDate: "2022-02-18T04:43:07Z",
    recommendation:
      "Destruction of Right Glenoid Cavity, Percutaneous Approach",
    modality: "Sm-to-sm bowel anastom",
    orderingDoctor: "Cart Bland",
  },
  {
    patientId: 15,
    patientName: "Gardener Mityashin",
    age: 51,
    studyDate: "2022-07-02T00:20:48Z",
    recommendation: "Destruction of Left Zygomatic Bone, Open Approach",
    modality: "Tot chest cage ostectomy",
    orderingDoctor: "Celestine Poulden",
  },
  {
    patientId: 16,
    patientName: "Herschel Espadate",
    age: 52,
    studyDate: "2022-09-07T05:35:34Z",
    recommendation:
      "Dilation of Right Radial Artery, Bifurcation, with Three Drug-eluting Intraluminal Devices, Percutaneous Approach",
    modality: "Cyclocryotherapy",
    orderingDoctor: "Raoul Woodhouse",
  },
  {
    patientId: 17,
    patientName: "Hamlen Louca",
    age: 38,
    studyDate: "2022-09-17T02:42:53Z",
    recommendation:
      "Introduction of Other Gas into Biliary and Pancreatic Tract, Via Natural or Artificial Opening",
    modality: "Re-entry operation",
    orderingDoctor: "Corrina Tatlow",
  },
  {
    patientId: 18,
    patientName: "Ade Giotto",
    age: 54,
    studyDate: "2021-09-29T19:28:04Z",
    recommendation:
      "Supplement Left Hip Muscle with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach",
    modality: "Laparoscopic oophorotomy",
    orderingDoctor: "Eziechiele Gainsburgh",
  },
  {
    patientId: 19,
    patientName: "Haydon Hutchason",
    age: 48,
    studyDate: "2021-10-18T15:00:42Z",
    recommendation:
      "Dilation of Middle Colic Artery, Bifurcation, with Four or More Drug-eluting Intraluminal Devices, Open Approach",
    modality: "Local excis breast les",
    orderingDoctor: "Bobbette Pencost",
  },
  {
    patientId: 20,
    patientName: "Bradford Griston",
    age: 73,
    studyDate: "2021-11-15T08:44:00Z",
    recommendation:
      "Extirpation of Matter from Right Innominate Vein, Open Approach",
    modality: "Nasal lesion excis NOS",
    orderingDoctor: "Kenny Doale",
  },
  {
    patientId: 21,
    patientName: "Moyra Mettricke",
    age: 58,
    studyDate: "2021-11-15T09:31:41Z",
    recommendation:
      "Restriction of Thoracic Aorta, Descending with Branched or Fenestrated Intraluminal Device, One or Two Arteries, Open Approach",
    modality: "Rect/perirect dx op NEC",
    orderingDoctor: "Arliene Orridge",
  },
  {
    patientId: 22,
    patientName: "Wilton Michelmore",
    age: 42,
    studyDate: "2021-11-27T14:24:36Z",
    recommendation:
      "Tomographic (Tomo) Nuclear Medicine Imaging of Chest and Abdomen using Indium 111 (In-111)",
    modality: "Enterovesico fist repair",
    orderingDoctor: "Cris Mollison",
  },
  {
    patientId: 23,
    patientName: "Gregory Cookman",
    age: 48,
    studyDate: "2022-06-09T09:30:19Z",
    recommendation:
      "Drainage of Right Upper Leg Subcutaneous Tissue and Fascia with Drainage Device, Percutaneous Approach",
    modality: "Remov thorax sutures",
    orderingDoctor: "Matteo d'Arcy",
  },
  {
    patientId: 24,
    patientName: "Puff Risso",
    age: 83,
    studyDate: "2022-08-15T03:51:36Z",
    recommendation:
      "Bypass Right Atrium to Left Pulmonary Artery with Autologous Arterial Tissue, Open Approach",
    modality: "Intestinal x-ray NEC",
    orderingDoctor: "Gerardo Lisciandro",
  },
  {
    patientId: 25,
    patientName: "Sena Brunel",
    age: 41,
    studyDate: "2022-08-29T20:09:14Z",
    recommendation:
      "Repair Right Foot Tendon, Percutaneous Endoscopic Approach",
    modality: "Dilation of intestine",
    orderingDoctor: "Kamila Vondrach",
  },
  {
    patientId: 26,
    patientName: "Berthe Gillebert",
    age: 73,
    studyDate: "2022-05-03T06:40:53Z",
    recommendation:
      "Bypass Peritoneal Cavity to Cutaneous with Synthetic Substitute, Percutaneous Approach",
    modality: "Lung laceration closure",
    orderingDoctor: "Brianna Roizn",
  },
  {
    patientId: 27,
    patientName: "Corey Kepp",
    age: 47,
    studyDate: "2022-06-17T18:22:53Z",
    recommendation:
      "Low Dose Rate (LDR) Brachytherapy of Duodenum using Iridium 192 (Ir-192)",
    modality: "Transplant hand tend NEC",
    orderingDoctor: "Orville Hartfleet",
  },
  {
    patientId: 28,
    patientName: "Dale McAuliffe",
    age: 46,
    studyDate: "2021-12-13T20:45:00Z",
    recommendation:
      "Drainage of Bilateral Spermatic Cords, Open Approach, Diagnostic",
    modality: "Conjunctivoplasty NEC",
    orderingDoctor: "Jules Barr",
  },
  {
    patientId: 29,
    patientName: "Isobel Arnald",
    age: 50,
    studyDate: "2022-04-09T00:50:48Z",
    recommendation:
      "Removal of Autologous Tissue Substitute from Mouth and Throat, Via Natural or Artificial Opening Endoscopic",
    modality: "Other thymus ops NOS",
    orderingDoctor: "Nisse Baleine",
  },
  {
    patientId: 30,
    patientName: "Tawnya Gainsborough",
    age: 53,
    studyDate: "2021-11-03T12:58:34Z",
    recommendation: "Drainage of Cul-de-sac, Open Approach",
    modality: "Reduction torsion testes",
    orderingDoctor: "Vinnie Costley",
  },
  {
    patientId: 31,
    patientName: "Shayne Van Ross",
    age: 18,
    studyDate: "2022-04-13T04:30:38Z",
    recommendation:
      "Bypass Innominate Artery to Right Lower Leg Artery with Nonautologous Tissue Substitute, Open Approach",
    modality: "Conjunctivorhinos w tube",
    orderingDoctor: "Brocky Rickeard",
  },
  {
    patientId: 32,
    patientName: "Meghan Hedylstone",
    age: 21,
    studyDate: "2022-07-24T15:21:08Z",
    recommendation:
      "Bypass Left Brachial Artery to Left Lower Arm Artery, Open Approach",
    modality: "Ventricl shunt-thorax",
    orderingDoctor: "Lurette Oxtarby",
  },
  {
    patientId: 33,
    patientName: "Harmon Gaul",
    age: 83,
    studyDate: "2022-02-08T23:00:29Z",
    recommendation:
      "Introduction of Nonautologous Somatic Stem Cells into Cranial Cavity and Brain, Open Approach",
    modality: "Tot ostect-tibia/fibula",
    orderingDoctor: "Carlen MacMaster",
  },
  {
    patientId: 34,
    patientName: "Trix Chowne",
    age: 53,
    studyDate: "2022-04-22T20:52:24Z",
    recommendation:
      "Repair Left External Auditory Canal, Percutaneous Endoscopic Approach",
    modality: "Foot & toe arthroscopy",
    orderingDoctor: "Kristopher Plaide",
  },
  {
    patientId: 35,
    patientName: "Gabriela Slowgrove",
    age: 80,
    studyDate: "2022-06-08T12:39:22Z",
    recommendation:
      "Low Dose Rate (LDR) Brachytherapy of Bladder using Iodine 125 (I-125)",
    modality: "Enterostomy NEC",
    orderingDoctor: "Ruthe Seaking",
  },
  {
    patientId: 36,
    patientName: "Karlen Shervil",
    age: 21,
    studyDate: "2022-04-09T09:27:11Z",
    recommendation:
      "Revision of Autologous Tissue Substitute in Upper Tendon, External Approach",
    modality: "Peripheral nerve suture",
    orderingDoctor: "Henderson McGray",
  },
  {
    patientId: 37,
    patientName: "Layne Clunan",
    age: 49,
    studyDate: "2022-05-04T17:44:06Z",
    recommendation:
      "Revision of Nonautologous Tissue Substitute in Right Metacarpophalangeal Joint, Percutaneous Approach",
    modality: "Forceps-aftercoming head",
    orderingDoctor: "Ken Khristoforov",
  },
  {
    patientId: 38,
    patientName: "Garner Norrington",
    age: 82,
    studyDate: "2022-07-01T06:47:18Z",
    recommendation:
      "Transfer Right Hand Muscle with Skin and Subcutaneous Tissue, Percutaneous Endoscopic Approach",
    modality: "Implt cochlear prost NOS",
    orderingDoctor: "Rochelle Trahearn",
  },
  {
    patientId: 39,
    patientName: "Klara Gudge",
    age: 41,
    studyDate: "2022-01-01T07:43:45Z",
    recommendation:
      "Replacement of Right Thumb Phalanx with Autologous Tissue Substitute, Open Approach",
    modality: "Release of chordee",
    orderingDoctor: "Cilka Caze",
  },
  {
    patientId: 40,
    patientName: "Julieta Geraudy",
    age: 34,
    studyDate: "2021-12-08T16:57:24Z",
    recommendation:
      "Drainage of Left Metatarsal-Tarsal Joint, Percutaneous Endoscopic Approach, Diagnostic",
    modality: "Epididymotomy",
    orderingDoctor: "Urbano Crowther",
  },
  {
    patientId: 41,
    patientName: "Marie Bright",
    age: 75,
    studyDate: "2022-04-06T20:15:40Z",
    recommendation:
      "Excision of Left Clavicle, Percutaneous Approach, Diagnostic",
    modality: "Therapeutc leukopheresis",
    orderingDoctor: "Justine McLagan",
  },
  {
    patientId: 42,
    patientName: "Katherina Calvey",
    age: 46,
    studyDate: "2021-11-28T00:56:02Z",
    recommendation:
      "Drainage of Cervix, Via Natural or Artificial Opening, Diagnostic",
    modality: "Inser temp pacemaker sys",
    orderingDoctor: "Maybelle Goodchild",
  },
  {
    patientId: 43,
    patientName: "Case Liddicoat",
    age: 80,
    studyDate: "2022-05-08T15:36:21Z",
    recommendation: "Obstetrics, Pregnancy, Delivery",
    modality: "Dilation of rectum",
    orderingDoctor: "Kin Butter",
  },
  {
    patientId: 44,
    patientName: "Blane McCloy",
    age: 52,
    studyDate: "2021-12-26T02:45:27Z",
    recommendation:
      "Drainage of Left Common Iliac Vein with Drainage Device, Percutaneous Approach",
    modality: "Removal trunk FB NEC",
    orderingDoctor: "Erick Biskupiak",
  },
  {
    patientId: 45,
    patientName: "Skelly Mailes",
    age: 50,
    studyDate: "2021-12-13T15:48:38Z",
    recommendation: "Repair Cerebral Ventricle, Percutaneous Approach",
    modality: "Intest stoma closure NOS",
    orderingDoctor: "Wynn Showalter",
  },
  {
    patientId: 46,
    patientName: "Jacquelin Morrad",
    age: 30,
    studyDate: "2022-08-20T20:01:10Z",
    recommendation:
      "Replacement of Superior Vena Cava with Zooplastic Tissue, Percutaneous Endoscopic Approach",
    modality: "Ant nasal pack for epist",
    orderingDoctor: "Britni Cristofolini",
  },
  {
    patientId: 47,
    patientName: "Mordecai Yurivtsev",
    age: 66,
    studyDate: "2021-10-28T15:56:28Z",
    recommendation:
      "Occlusion of Ampulla of Vater with Extraluminal Device, Open Approach",
    modality: "Delay opening colostomy",
    orderingDoctor: "Andy Thraves",
  },
  {
    patientId: 48,
    patientName: "Dennet Cawthery",
    age: 22,
    studyDate: "2021-11-12T00:42:37Z",
    recommendation:
      "Transfusion of Nonautologous Whole Blood into Peripheral Vein, Percutaneous Approach",
    modality: "Excis ampulla of vater",
    orderingDoctor: "Robena Pickrell",
  },
  {
    patientId: 49,
    patientName: "Averil Leads",
    age: 70,
    studyDate: "2022-06-02T17:53:26Z",
    recommendation:
      "Removal of Autologous Tissue Substitute from Right Humeral Head, Open Approach",
    modality: "Other femoral incision",
    orderingDoctor: "Merrill Kubat",
  },
  {
    patientId: 50,
    patientName: "Tersina Turnbull",
    age: 68,
    studyDate: "2021-12-10T00:03:24Z",
    recommendation:
      "Removal of Monitoring Device from Upper Intestinal Tract, Percutaneous Approach",
    modality: "Implant mechanic kidney",
    orderingDoctor: "Yul Battabee",
  },
  {
    patientId: 51,
    patientName: "Isa Drews",
    age: 35,
    studyDate: "2021-10-17T11:36:32Z",
    recommendation:
      "Revision of Drainage Device in Face, Percutaneous Approach",
    modality: "Lid reconstruction NOS",
    orderingDoctor: "Beatrix Whether",
  },
  {
    patientId: 52,
    patientName: "Anatollo Cartmell",
    age: 29,
    studyDate: "2022-03-17T09:10:51Z",
    recommendation: "Beam Radiation of Axillary Lymphatics using Electrons",
    modality: "Vocational rehabilitat",
    orderingDoctor: "Janith Coyett",
  },
  {
    patientId: 53,
    patientName: "Gracia Pulhoster",
    age: 34,
    studyDate: "2022-02-05T17:00:20Z",
    recommendation:
      "Supplement Optic Nerve with Autologous Tissue Substitute, Percutaneous Approach",
    modality: "Destruct facial bone les",
    orderingDoctor: "Ardys McIlvaney",
  },
  {
    patientId: 54,
    patientName: "Dasya Esposita",
    age: 33,
    studyDate: "2021-10-23T08:12:06Z",
    recommendation: "Beam Radiation of Whole Body using Neutrons",
    modality: "Contr pulmon arteriogram",
    orderingDoctor: "Raymond Kornilyev",
  },
  {
    patientId: 55,
    patientName: "Archibald Compfort",
    age: 42,
    studyDate: "2021-11-09T08:53:25Z",
    recommendation:
      "Supplement Right Sternoclavicular Joint with Autologous Tissue Substitute, Percutaneous Approach",
    modality: "Hemorrhoid reduction",
    orderingDoctor: "Betty Moynihan",
  },
  {
    patientId: 56,
    patientName: "Giacobo Korneichuk",
    age: 27,
    studyDate: "2022-03-20T12:21:27Z",
    recommendation:
      "Dilation of Left Innominate Vein with Intraluminal Device, Open Approach",
    modality: "Revise sm bowel anastom",
    orderingDoctor: "Pembroke Collcott",
  },
  {
    patientId: 57,
    patientName: "Jelene Fernez",
    age: 67,
    studyDate: "2022-08-21T12:20:35Z",
    recommendation:
      "Replacement of Right Upper Eyelid with Nonautologous Tissue Substitute, External Approach",
    modality: "Percut prostatic aspirat",
    orderingDoctor: "Niles Sturte",
  },
  {
    patientId: 58,
    patientName: "Salvidor Lascell",
    age: 37,
    studyDate: "2022-08-17T10:26:36Z",
    recommendation:
      "Insertion of Infusion Device into Ileum, Percutaneous Approach",
    modality: "Bile duct incision NEC",
    orderingDoctor: "Dane Coggon",
  },
  {
    patientId: 59,
    patientName: "Norry Yakhin",
    age: 74,
    studyDate: "2022-01-07T06:04:08Z",
    recommendation:
      "Muscle Performance Assessment of Integumentary System - Upper Back / Upper Extremity using Assistive, Adaptive, Supportive or Protective Equipment",
    modality: "Opn fx red w int fix NEC",
    orderingDoctor: "Grange Niave",
  },
  {
    patientId: 60,
    patientName: "Jada O'Neill",
    age: 24,
    studyDate: "2021-10-19T16:22:20Z",
    recommendation:
      "Drainage of Left Shoulder Bursa and Ligament, Open Approach",
    modality: "Isotope inject/instill",
    orderingDoctor: "Trefor Larret",
  },
  {
    patientId: 61,
    patientName: "Emanuel Marchington",
    age: 22,
    studyDate: "2022-08-06T17:47:13Z",
    recommendation:
      "Extirpation of Matter from Left Subclavian Artery, Open Approach",
    modality: "Thoracoscopic pleural bx",
    orderingDoctor: "Goldi Crawforth",
  },
  {
    patientId: 62,
    patientName: "Ben Bunn",
    age: 80,
    studyDate: "2022-07-30T07:33:54Z",
    recommendation:
      "Transplantation of Large Intestine, Zooplastic, Open Approach",
    modality: "Cde for calculus remov",
    orderingDoctor: "Juliann Bending",
  },
  {
    patientId: 63,
    patientName: "Fremont Jelf",
    age: 48,
    studyDate: "2022-04-04T23:50:25Z",
    recommendation: "Extraction of Left Vocal Cord, Open Approach",
    modality: "Culture-endocrine",
    orderingDoctor: "Izzy Lillo",
  },
  {
    patientId: 64,
    patientName: "Catharine Dulany",
    age: 57,
    studyDate: "2022-09-13T13:20:09Z",
    recommendation: "Release Left Hip Joint, External Approach",
    modality: "Culture-bili/pancreas",
    orderingDoctor: "Con Withringten",
  },
  {
    patientId: 65,
    patientName: "Sander Flowers",
    age: 64,
    studyDate: "2021-11-14T00:12:29Z",
    recommendation:
      "Restriction of Right Middle Lobe Bronchus with Intraluminal Device, Percutaneous Endoscopic Approach",
    modality: "Debrid opn fx-finger",
    orderingDoctor: "Berte Haxby",
  },
  {
    patientId: 66,
    patientName: "Dorelia Matuszyk",
    age: 20,
    studyDate: "2022-07-22T15:24:05Z",
    recommendation: "Destruction of Lower Vein, Percutaneous Approach",
    modality: "Anesthetized eye exam",
    orderingDoctor: "Isador Fairholm",
  },
  {
    patientId: 67,
    patientName: "Drake Hunnaball",
    age: 72,
    studyDate: "2022-07-11T14:46:38Z",
    recommendation:
      "Alteration of Right Lower Extremity with Synthetic Substitute, Percutaneous Approach",
    modality: "Dilat frontonasal duct",
    orderingDoctor: "Haskell Whittock",
  },
  {
    patientId: 68,
    patientName: "Hadrian Whittlesea",
    age: 80,
    studyDate: "2022-06-07T10:09:21Z",
    recommendation: "Repair Left Metacarpal, Open Approach",
    modality: "Permanent ileostomy NEC",
    orderingDoctor: "Sergei Yitzhakov",
  },
  {
    patientId: 69,
    patientName: "Dame Kibel",
    age: 48,
    studyDate: "2022-01-30T07:15:45Z",
    recommendation:
      "Division of Left Abdomen Tendon, Percutaneous Endoscopic Approach",
    modality: "C & s-integument",
    orderingDoctor: "Herrick Waskett",
  },
  {
    patientId: 70,
    patientName: "Cass Caveau",
    age: 67,
    studyDate: "2021-11-04T11:43:36Z",
    recommendation:
      "Supplement Stomach, Pylorus with Nonautologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic",
    modality: "Manual removal-placenta",
    orderingDoctor: "Sibbie Whyler",
  },
  {
    patientId: 71,
    patientName: "Belicia Rodda",
    age: 81,
    studyDate: "2022-09-28T12:29:25Z",
    recommendation: "Beam Radiation of Liver using Electrons, Intraoperative",
    modality: "Closure of anal fistula",
    orderingDoctor: "Seymour Guiot",
  },
  {
    patientId: 72,
    patientName: "Addie Downer",
    age: 84,
    studyDate: "2022-02-11T06:45:34Z",
    recommendation:
      "Alteration of Lower Back with Synthetic Substitute, Open Approach",
    modality: "Nasophary contrast x-ray",
    orderingDoctor: "Tabbitha Pople",
  },
  {
    patientId: 73,
    patientName: "Edy Cunah",
    age: 44,
    studyDate: "2022-03-13T05:50:05Z",
    recommendation:
      "Bypass Left Hypogastric Vein to Lower Vein with Autologous Tissue Substitute, Open Approach",
    modality: "Coronar arteriogr-1 cath",
    orderingDoctor: "Jae Morling",
  },
  {
    patientId: 74,
    patientName: "Carleen Danick",
    age: 26,
    studyDate: "2022-07-17T18:25:41Z",
    recommendation:
      "Revision of Synthetic Substitute in Right Knee Joint, Open Approach",
    modality: "Lap hern ant abd-gft NEC",
    orderingDoctor: "Glynda Bletcher",
  },
  {
    patientId: 75,
    patientName: "Umeko Towl",
    age: 62,
    studyDate: "2021-10-02T13:45:42Z",
    recommendation:
      "Replacement of Nose with Autologous Tissue Substitute, External Approach",
    modality: "Remove imp device-femur",
    orderingDoctor: "Chaim Sandys",
  },
  {
    patientId: 76,
    patientName: "Stevena Buddell",
    age: 73,
    studyDate: "2021-12-05T13:08:24Z",
    recommendation:
      "Imaging, Axial Skeleton, Except Skull and Facial Bones, Fluoroscopy",
    modality: "Fus/refus 2-3 vertebrae",
    orderingDoctor: "Emma Kinson",
  },
  {
    patientId: 77,
    patientName: "Lida Simenon",
    age: 80,
    studyDate: "2022-05-12T00:02:14Z",
    recommendation:
      "Fusion of Left Temporomandibular Joint with Synthetic Substitute, Percutaneous Approach",
    modality: "Spine meningocele repair",
    orderingDoctor: "Cherish Pidgin",
  },
  {
    patientId: 78,
    patientName: "Shandie Marrows",
    age: 33,
    studyDate: "2022-08-11T23:50:00Z",
    recommendation:
      "Transplantation of Lymphatics and Hemic into Products of Conception, Percutaneous Endoscopic Approach",
    modality: "Soft tissue aspirat NEC",
    orderingDoctor: "Scott Olland",
  },
  {
    patientId: 79,
    patientName: "Alejandro Eatttok",
    age: 51,
    studyDate: "2022-02-17T18:40:28Z",
    recommendation:
      "Removal of Autologous Tissue Substitute from Left Eye, Percutaneous Approach",
    modality: "Toxicology-eye",
    orderingDoctor: "Donica Morot",
  },
  {
    patientId: 80,
    patientName: "Margalo Glyn",
    age: 37,
    studyDate: "2022-04-09T22:42:57Z",
    recommendation:
      "Replacement of Right Peroneal Artery with Synthetic Substitute, Percutaneous Endoscopic Approach",
    modality: "Lap unilat oophorectomy",
    orderingDoctor: "Delmore Alliston",
  },
  {
    patientId: 81,
    patientName: "Otho Lindelof",
    age: 26,
    studyDate: "2021-10-06T22:55:40Z",
    recommendation:
      "Bypass Left Fallopian Tube to Right Fallopian Tube with Autologous Tissue Substitute, Percutaneous Endoscopic Approach",
    modality: "Unilat fallop tube destr",
    orderingDoctor: "Alford Sancraft",
  },
  {
    patientId: 82,
    patientName: "Melodee Ropkes",
    age: 21,
    studyDate: "2022-02-09T16:04:04Z",
    recommendation:
      "Supplement Left Knee Joint with Synthetic Substitute, Open Approach",
    modality: "Proc-vessel bifurcation",
    orderingDoctor: "Dame Adan",
  },
  {
    patientId: 83,
    patientName: "Kordula Strelitzer",
    age: 72,
    studyDate: "2021-11-14T08:18:28Z",
    recommendation: "Release Left Carotid Body, Percutaneous Approach",
    modality: "Scleral operation NEC",
    orderingDoctor: "Cos Youngs",
  },
  {
    patientId: 84,
    patientName: "Fidelia Hovel",
    age: 55,
    studyDate: "2022-06-03T01:01:23Z",
    recommendation:
      "Removal of Drainage Device from Pancreas, External Approach",
    modality: "Excise minor les lid NEC",
    orderingDoctor: "Modesty O'Sesnane",
  },
  {
    patientId: 85,
    patientName: "Lexine Moyler",
    age: 30,
    studyDate: "2022-03-04T21:46:19Z",
    recommendation: "Repair Right Inferior Parathyroid Gland, Open Approach",
    modality: "Up limb sft tis xray NEC",
    orderingDoctor: "Dulci Tarquini",
  },
  {
    patientId: 86,
    patientName: "Normy Chatell",
    age: 32,
    studyDate: "2022-04-01T10:11:02Z",
    recommendation:
      "Chiropractic Manipulation of Lower Extremities, Direct Visceral",
    modality: "Irrigate/expl vent shunt",
    orderingDoctor: "Eduino Rounce",
  },
  {
    patientId: 87,
    patientName: "Mort Coldtart",
    age: 26,
    studyDate: "2022-08-21T18:24:33Z",
    recommendation:
      "Restriction of Right Internal Mammary Lymphatic, Open Approach",
    modality: "Cholecystotomy NEC",
    orderingDoctor: "Rowena Bonnesen",
  },
  {
    patientId: 88,
    patientName: "Daven Reames",
    age: 84,
    studyDate: "2022-03-22T02:03:07Z",
    recommendation:
      "Removal of Synthetic Substitute from Right Hip Joint, Acetabular Surface, Open Approach",
    modality: "Frontal sinusotomy",
    orderingDoctor: "Blinnie Colvine",
  },
  {
    patientId: 89,
    patientName: "Romeo Crilley",
    age: 19,
    studyDate: "2021-11-18T02:00:21Z",
    recommendation:
      "Introduction of Other Antineoplastic into Subcutaneous Tissue, Percutaneous Approach",
    modality: "Esophageal graft NEC",
    orderingDoctor: "Wolfy Roggero",
  },
  {
    patientId: 90,
    patientName: "Ginger Robinett",
    age: 19,
    studyDate: "2021-10-13T20:22:47Z",
    recommendation: "Transfer Peroneal Nerve to Peroneal Nerve, Open Approach",
    modality: "Periop aut trans hol bld",
    orderingDoctor: "Correy Chifney",
  },
  {
    patientId: 91,
    patientName: "Lucio Jupp",
    age: 44,
    studyDate: "2021-10-01T02:29:54Z",
    recommendation: "Drainage of Lumbosacral Disc, Open Approach, Diagnostic",
    modality: "Exc pituit les-transphen",
    orderingDoctor: "Dolley Iacovolo",
  },
  {
    patientId: 92,
    patientName: "Donavon Facer",
    age: 68,
    studyDate: "2022-05-11T15:59:51Z",
    recommendation:
      "Supplement Left Tarsal with Synthetic Substitute, Percutaneous Approach",
    modality: "Removal FB from arm",
    orderingDoctor: "Valene Whipp",
  },
  {
    patientId: 93,
    patientName: "Lind Mendez",
    age: 42,
    studyDate: "2022-07-29T04:24:16Z",
    recommendation: "Excision of Left Humeral Head, Open Approach",
    modality: "Ins tot disc prost cerv",
    orderingDoctor: "Angus Jeynes",
  },
  {
    patientId: 94,
    patientName: "Julia Isakovic",
    age: 23,
    studyDate: "2022-09-23T01:42:06Z",
    recommendation: "Plain Radiography of Sacroiliac Joints",
    modality: "Closed pancreatic biopsy",
    orderingDoctor: "Teodoor Bullon",
  },
  {
    patientId: 95,
    patientName: "Harmonia Ashment",
    age: 18,
    studyDate: "2021-12-22T07:56:28Z",
    recommendation:
      "Dilation of Right Hand Artery, Bifurcation, with Intraluminal Device, Open Approach",
    modality: "Bilat tubal destruct NEC",
    orderingDoctor: "Alejandra Giovannacc@i",
  },
  {
    patientId: 96,
    patientName: "Rosella Flavelle",
    age: 25,
    studyDate: "2022-03-15T10:39:39Z",
    recommendation: "Revision of Intraluminal Device in Bladder, Open Approach",
    modality: "Refus lmb/lmbsc ant/post",
    orderingDoctor: "Cordi Heymann",
  },
  {
    patientId: 97,
    patientName: "Viviana Petrovykh",
    age: 30,
    studyDate: "2022-01-29T18:14:53Z",
    recommendation:
      "Drainage of Cecum, Via Natural or Artificial Opening, Diagnostic",
    modality: "TRAM flap, free",
    orderingDoctor: "Christean Skeels",
  },
  {
    patientId: 98,
    patientName: "Leeanne Middleweek",
    age: 52,
    studyDate: "2022-02-24T02:28:30Z",
    recommendation: "Release Lumbosacral Joint, External Approach",
    modality: "Intra-abd sm bowel manip",
    orderingDoctor: "Lockwood Esposito",
  },
  {
    patientId: 99,
    patientName: "Madalyn Enticknap",
    age: 45,
    studyDate: "2022-03-24T20:03:49Z",
    recommendation: "Compression of Left Finger using Pressure Dressing",
    modality: "Destruc-elbow lesion NEC",
    orderingDoctor: "Margarette Cotterill",
  },
  {
    patientId: 100,
    patientName: "Marcello Yacobsohn",
    age: 22,
    studyDate: "2022-07-15T05:43:37Z",
    recommendation:
      "Destruction of Lumbar Vertebral Joint, Percutaneous Endoscopic Approach",
    modality: "Open reduction nasal fx",
    orderingDoctor: "Milly MacMarcuis",
  },
];
